open Core
open! Import

let%expect_test "small number Diffie-Hellman" =
  (* big_a, big_b are public keys; a, b are corresponding private keys *)
  let big_a, a = Diffie_hellman.Small.gen_key () in
  let big_b, b = Diffie_hellman.Small.gen_key () in
  (* s and s' should be the same - s can be generated by the holder of private
  key a, and s' by the holder of private key b. s can't be generated without at
  least one of the private keys *)
  let s = Diffie_hellman.Small.session ~my_priv:a ~peer_pub:big_b in
  let s' = Diffie_hellman.Small.session ~my_priv:b ~peer_pub:big_a in
  assert (Z.equal s s');
  [%expect {||}]

let%expect_test "normal D-H" =
  let big_a, a = Diffie_hellman.gen_key () in
  let big_b, b = Diffie_hellman.gen_key () in
  let s = Diffie_hellman.session ~my_priv:a ~peer_pub:big_b in
  let s' = Diffie_hellman.session ~my_priv:b ~peer_pub:big_a in
  assert (Z.equal s s');
  [%expect {||}]
